/**
 * Tabela CFOP — Codigos Fiscais de Operacoes e Prestacoes.
 * Agrupados por tipo de operacao.
 */

/** Saidas internas (dentro do estado) */
export const CFOP_SAIDA_INTERNA: Record<string, string> = {
  '5101': 'Venda de producao do estabelecimento',
  '5102': 'Venda de mercadoria adquirida ou recebida de terceiros',
  '5103': 'Venda de producao do estabelecimento efetuada fora do estabelecimento',
  '5104': 'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento',
  '5105': 'Venda de producao do estabelecimento que nao deva por ele transitar',
  '5106': 'Venda de mercadoria adquirida ou recebida de terceiros, que nao deva por ele transitar',
  '5109': 'Venda de producao do estabelecimento destinada a Zona Franca de Manaus ou Areas de Livre Comercio',
  '5110': 'Venda de mercadoria adquirida ou recebida de terceiros, destinada a Zona Franca de Manaus ou Areas de Livre Comercio',
  '5111': 'Venda de producao do estabelecimento remetida anteriormente em consignacao industrial',
  '5112': 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignacao industrial',
  '5113': 'Venda de producao do estabelecimento remetida anteriormente em consignacao mercantil',
  '5114': 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignacao mercantil',
  '5115': 'Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignacao mercantil',
  '5116': 'Venda de producao do estabelecimento originada de encomenda para entrega futura',
  '5117': 'Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura',
  '5118': 'Venda de producao do estabelecimento entregue ao destinatario por conta e ordem do adquirente originario',
  '5119': 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatario por conta e ordem do adquirente originario',
  '5120': 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatario pelo vendedor remetente',
  '5122': 'Venda de producao do estabelecimento remetida para industrializacao por conta e ordem do adquirente',
  '5123': 'Venda de mercadoria adquirida ou recebida de terceiros remetida para industrializacao por conta e ordem do adquirente',
  '5124': 'Industrializacao efetuada para outra empresa',
  '5125': 'Industrializacao efetuada para outra empresa quando a mercadoria recebida para utilizacao no processo de industrializacao nao transitar pelo estabelecimento adquirente da mercadoria',
  '5151': 'Transferencia de producao do estabelecimento',
  '5152': 'Transferencia de mercadoria adquirida ou recebida de terceiros',
  '5153': 'Transferencia de energia eletrica',
  '5155': 'Transferencia de producao do estabelecimento que nao deva por ele transitar',
  '5156': 'Transferencia de mercadoria adquirida ou recebida de terceiros que nao deva por ele transitar',
  '5201': 'Devolucao de compra para industrializacao',
  '5202': 'Devolucao de compra para comercializacao',
  '5205': 'Anulacao de valor relativo a aquisicao de servico de comunicacao',
  '5206': 'Anulacao de valor relativo a aquisicao de servico de transporte',
  '5207': 'Anulacao de valor relativo a compra de energia eletrica',
  '5208': 'Devolucao de mercadoria recebida em transferencia para industrializacao',
  '5209': 'Devolucao de mercadoria recebida em transferencia para comercializacao',
  '5210': 'Devolucao de compra para utilizacao na prestacao de servico',
  '5401': 'Venda de producao do estabelecimento em operacao com produto sujeito ao regime de substituicao tributaria na condicao de contribuinte substituto',
  '5402': 'Venda de producao do estabelecimento de produto sujeito ao regime de substituicao tributaria em operacao entre contribuintes substitutos do mesmo produto',
  '5403': 'Venda de mercadoria adquirida ou recebida de terceiros em operacao com mercadoria sujeita ao regime de substituicao tributaria na condicao de contribuinte substituto',
  '5405': 'Venda de mercadoria adquirida ou recebida de terceiros em operacao com mercadoria sujeita ao regime de substituicao tributaria na condicao de contribuinte substituido',
  '5411': 'Devolucao de compra para industrializacao em operacao com mercadoria sujeita ao regime de substituicao tributaria',
  '5412': 'Devolucao de compra para comercializacao em operacao com mercadoria sujeita ao regime de substituicao tributaria',
  '5413': 'Devolucao de mercadoria destinada ao uso ou consumo em operacao com mercadoria sujeita ao regime de substituicao tributaria',
  '5414': 'Devolucao de compra para ativo imobilizado em operacao com mercadoria sujeita ao regime de substituicao tributaria',
  '5415': 'Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento em operacao com mercadoria sujeita ao regime de substituicao tributaria',
  '5551': 'Venda de bem do ativo imobilizado',
  '5552': 'Transferencia de bem do ativo imobilizado',
  '5553': 'Devolucao de compra de bem para o ativo imobilizado',
  '5554': 'Remessa de bem do ativo imobilizado para uso fora do estabelecimento',
  '5555': 'Devolucao de bem do ativo imobilizado de terceiro recebido para uso no estabelecimento',
  '5556': 'Devolucao de compra de material de uso ou consumo',
  '5557': 'Transferencia de material de uso ou consumo',
  '5901': 'Remessa para industrializacao por encomenda',
  '5902': 'Retorno de mercadoria utilizada na industrializacao por encomenda',
  '5903': 'Retorno de mercadoria recebida para industrializacao e nao aplicada no referido processo',
  '5904': 'Remessa para venda fora do estabelecimento',
  '5905': 'Remessa para deposito fechado ou armazem geral',
  '5906': 'Retorno de mercadoria depositada em deposito fechado ou armazem geral',
  '5910': 'Remessa em bonificacao doacao ou brinde',
  '5911': 'Remessa de amostra gratis',
  '5912': 'Remessa de mercadoria ou bem para demonstracao',
  '5913': 'Retorno de mercadoria ou bem recebido para demonstracao',
  '5914': 'Remessa de mercadoria ou bem para exposicao ou feira',
  '5915': 'Remessa de mercadoria ou bem para conserto ou reparo',
  '5916': 'Retorno de mercadoria ou bem recebido para conserto ou reparo',
  '5917': 'Remessa de mercadoria em consignacao mercantil ou industrial',
  '5918': 'Devolucao de mercadoria recebida em consignacao mercantil ou industrial',
  '5919': 'Devolucao simbolica de mercadoria vendida ou utilizada em processo industrial recebida anteriormente em consignacao mercantil ou industrial',
  '5920': 'Remessa de vasilhame ou sacaria',
  '5921': 'Devolucao de vasilhame ou sacaria',
  '5922': 'Lancamento efetuado a titulo de simples faturamento decorrente de venda para entrega futura',
  '5923': 'Remessa de mercadoria por conta e ordem de terceiros em venda a ordem',
  '5924': 'Remessa para industrializacao por conta e ordem do adquirente da mercadoria quando esta nao transitar pelo estabelecimento do adquirente',
  '5925': 'Retorno de mercadoria recebida para industrializacao por conta e ordem do adquirente da mercadoria quando aquela nao transitar pelo estabelecimento do adquirente',
  '5929': 'Lancamento efetuado em decorrencia de emissao de documento fiscal relativo a operacao ou prestacao tambem registrada em equipamento Emissor de Cupom Fiscal',
  '5949': 'Outra saida de mercadoria ou prestacao de servico nao especificado'
};

/** Saidas interestaduais */
export const CFOP_SAIDA_INTERESTADUAL: Record<string, string> = {
  '6101': 'Venda de producao do estabelecimento',
  '6102': 'Venda de mercadoria adquirida ou recebida de terceiros',
  '6103': 'Venda de producao do estabelecimento efetuada fora do estabelecimento',
  '6104': 'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento',
  '6105': 'Venda de producao do estabelecimento que nao deva por ele transitar',
  '6106': 'Venda de mercadoria adquirida ou recebida de terceiros, que nao deva por ele transitar',
  '6107': 'Venda de producao do estabelecimento destinada a nao contribuinte',
  '6108': 'Venda de mercadoria adquirida ou recebida de terceiros destinada a nao contribuinte',
  '6109': 'Venda de producao do estabelecimento destinada a Zona Franca de Manaus ou Areas de Livre Comercio',
  '6110': 'Venda de mercadoria adquirida ou recebida de terceiros, destinada a Zona Franca de Manaus ou Areas de Livre Comercio',
  '6116': 'Venda de producao do estabelecimento originada de encomenda para entrega futura',
  '6117': 'Venda de mercadoria adquirida ou recebida de terceiros originada de encomenda para entrega futura',
  '6122': 'Venda de producao do estabelecimento remetida para industrializacao por conta e ordem do adquirente',
  '6123': 'Venda de mercadoria adquirida ou recebida de terceiros remetida para industrializacao por conta e ordem do adquirente',
  '6124': 'Industrializacao efetuada para outra empresa',
  '6151': 'Transferencia de producao do estabelecimento',
  '6152': 'Transferencia de mercadoria adquirida ou recebida de terceiros',
  '6155': 'Transferencia de producao do estabelecimento que nao deva por ele transitar',
  '6156': 'Transferencia de mercadoria adquirida ou recebida de terceiros que nao deva por ele transitar',
  '6201': 'Devolucao de compra para industrializacao',
  '6202': 'Devolucao de compra para comercializacao',
  '6208': 'Devolucao de mercadoria recebida em transferencia para industrializacao',
  '6209': 'Devolucao de mercadoria recebida em transferencia para comercializacao',
  '6401': 'Venda de producao do estabelecimento em operacao com produto sujeito ao regime de substituicao tributaria na condicao de contribuinte substituto',
  '6403': 'Venda de mercadoria adquirida ou recebida de terceiros em operacao com mercadoria sujeita ao regime de substituicao tributaria na condicao de contribuinte substituto',
  '6949': 'Outra saida de mercadoria ou prestacao de servico nao especificado'
};

/** Entradas internas (dentro do estado) */
export const CFOP_ENTRADA_INTERNA: Record<string, string> = {
  '1101': 'Compra para industrializacao',
  '1102': 'Compra para comercializacao',
  '1111': 'Compra para industrializacao de mercadoria recebida anteriormente em consignacao industrial',
  '1113': 'Compra para comercializacao de mercadoria recebida anteriormente em consignacao mercantil',
  '1116': 'Compra para industrializacao originada de encomenda para recebimento futuro',
  '1117': 'Compra para comercializacao originada de encomenda para recebimento futuro',
  '1120': 'Compra para industrializacao em que a mercadoria foi remetida pelo fornecedor ao industrializador',
  '1121': 'Compra para comercializacao em que a mercadoria foi remetida pelo fornecedor ao industrializador',
  '1122': 'Compra para industrializacao em que a mercadoria foi remetida pelo fornecedor diretamente ao adquirente da mercadoria',
  '1124': 'Industrializacao efetuada por outra empresa',
  '1125': 'Industrializacao efetuada por outra empresa quando a mercadoria remetida para utilizacao no processo de industrializacao nao transitou pelo estabelecimento adquirente',
  '1126': 'Compra para utilizacao na prestacao de servico',
  '1151': 'Transferencia para industrializacao',
  '1152': 'Transferencia para comercializacao',
  '1201': 'Devolucao de venda de producao do estabelecimento',
  '1202': 'Devolucao de venda de mercadoria adquirida ou recebida de terceiros',
  '1401': 'Compra para industrializacao em operacao com mercadoria sujeita ao regime de substituicao tributaria',
  '1403': 'Compra para comercializacao em operacao com mercadoria sujeita ao regime de substituicao tributaria',
  '1551': 'Compra de bem para o ativo imobilizado',
  '1556': 'Compra de material para uso ou consumo',
  '1949': 'Outra entrada de mercadoria ou prestacao de servico nao especificado'
};

/** Entradas interestaduais */
export const CFOP_ENTRADA_INTERESTADUAL: Record<string, string> = {
  '2101': 'Compra para industrializacao',
  '2102': 'Compra para comercializacao',
  '2151': 'Transferencia para industrializacao',
  '2152': 'Transferencia para comercializacao',
  '2201': 'Devolucao de venda de producao do estabelecimento',
  '2202': 'Devolucao de venda de mercadoria adquirida ou recebida de terceiros',
  '2401': 'Compra para industrializacao em operacao com mercadoria sujeita ao regime de substituicao tributaria',
  '2403': 'Compra para comercializacao em operacao com mercadoria sujeita ao regime de substituicao tributaria',
  '2551': 'Compra de bem para o ativo imobilizado',
  '2556': 'Compra de material para uso ou consumo',
  '2949': 'Outra entrada de mercadoria ou prestacao de servico nao especificado'
};
